export const data = ["RAM", "KRISHNA", "KRISH","ABHI", 
"ABHIJIT1", "ABHIJIT2","GOVINDA", "TWITTER", "FACEBOOK", "SYSTEM", 
"LIKE", "AMAZON","TIGER", "SACHIN","MYNTRA", "MANGO",
"ABHIJIT21","ABHIJIT22","ABHIJIT23",
"ABHIJIT24", "ABHIJIT25", "ABHIJIT26", "ABHIJIT27","ABHIJIT28","ABHIJIT29","ABHIJIT3"];